### ISSUE TITLE
Packages without description display the message "undefined"

### ISSUE THREAD

**Issue by felladrin** [felladrin/PickBetterPack#280]
### Bug description

Packages without description display the message "undefined".
It could display "No description available" instead.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/418083/214185128-f2d3a261-a53c-4ab8-8c56-f907e496d3e8.png">

**Comment by Tejasbankar** [comment]
Hi @felladrin ,
Please check https://github.com/felladrin/PickBetterPack/pull/282.
