### ISSUE TITLE
Packages should have description sanitized

### ISSUE THREAD

**Issue by felladrin** [felladrin/PickBetterPack#281]
### Bug description

Packages should have their description sanitized to avoid the following:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/418083/214185700-71adbfad-635b-4916-a130-1dfa659a0aef.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/418083/214185778-208f962f-625d-40b2-9202-03ec3577d8b7.png">

**Comment by Tejasbankar** [comment]
Hi @felladrin ,
would be happy to work on this but can you explain how the description should be?
